version: '3.1'

services:
  micro-proxy:
    image: micro/micro:latest
    command: proxy
    environment:
      MICRO_SERVER_ADDRESS: ":9090"
    ports:
      - 9090:9090
  micro-web:
    image: micro/micro:latest
    command: web
    ports:
      - 8082:8082
  micro-api:
    image: micro/micro:latest
    command: api
    ports:
      - 8080:8080

  consignment-service:
    build: ./srv/consignment
    environment:
      MICRO_SERVER_ADDRESS: ":50501"
      MICRO_LOG_LEVEL: "debug"
      DB_HOST: "datastore:27017"
    ports:
      - 50501
  
  vessel-service:
    build: ./srv/vessel
    environment:
      MICRO_LOG_LEVEL: "debug"
      DB_HOST: "datastore:27017"

  user-service:
    build: ./srv/user
    environment:
      MICRO_LOG_LEVEL: "debug"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database

  datastore:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432

  adminer:
    image: dockette/adminer:full
    depends_on:
      - datastore
      - database
    ports:
      - 8700:80

